# Generated by Django 5.1 on 2024-08-23 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_student', models.CharField(choices=[('Parent', 'Parent'), ('Student', 'Student')], max_length=9)),
                ('l_name', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phoneNumber', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=30)),
                ('nearest_bus_stop', models.CharField(max_length=60)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=100)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.step1')),
            ],
        ),
        migrations.CreateModel(
            name='AboutTheChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('child_class', models.CharField(choices=[('Preschool', 'Preschool'), ('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Elementary 1', 'Elementary 1'), ('Elementary 2', 'Elementary 2'), ('Elementary 3', 'Elementary 3'), ('Elementary 4', 'Elementary 4'), ('Elementary 5', 'Elementary 5'), ('Elementary 6', 'Elementary 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=13)),
                ('subject', models.CharField(max_length=50)),
                ('goal', models.CharField(choices=[('WAEC/ NECO/ UME/ JUPEB', 'WAEC/ NECO/ UME/ JUPEB'), ('Primary School Leaving Certificate Examination (PSLCE)', 'Primary School Leaving Certificate Examination (PSLCE)'), ('Basic Education Certificate Examination (BECE)', 'Basic Education Certificate Examination (BECE)'), ('National Common Entrance Examination (NCEE)', 'National Common Entrance Examination (NCEE)'), ('Homework/ Revision/ Study help', 'Homework/ Revision/ Study help')], max_length=80)),
                ('school_curriculum', models.CharField(choices=[('Nigerian', 'Nigerian'), ('American', 'American'), ('British', 'British'), ('Not sure', 'Not sure')], max_length=10)),
                ('tutor_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any gender is fine', 'Any gender is fine')], max_length=19)),
                ('about_the_child', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.step1')),
            ],
        ),
        migrations.CreateModel(
            name='Step3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_available', models.JSONField()),
                ('hours_per_day', models.CharField(choices=[('One hour', 'One hour'), ('Two hours', 'Two hours'), ('Three hours', 'Three hours'), ('Four hours', 'Four hours'), ('Five hours', 'Five hours')], max_length=12)),
                ('preferred_time', models.CharField(choices=[('11:00am', '11:00am'), ('11:30am', '11:30am'), ('12:00pm', '12:00pm'), ('12:30pm', '12:30pm'), ('1:00pm', '1:00pm'), ('1:30pm', '1:30pm'), ('2:00pm', '2:00pm'), ('2:30pm', '2:30pm'), ('3:00pm', '3:00pm'), ('3:30pm', '3:30pm'), ('4:00pm', '4:00pm'), ('4:30pm', '4:30pm'), ('5:00pm', '5:00pm'), ('5:30pm', '5:30pm')], max_length=9)),
                ('teaching_mode', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical')], max_length=8)),
                ('how_long', models.CharField(choices=[('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('Monthly', 'Monthly')], max_length=10)),
                ('to_start_how_soon', models.CharField(choices=[('In a few days', 'In a few days'), ('Immediately', 'Immediately'), ('In a few weeks', 'In a few weeks')], max_length=20)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.step1')),
            ],
        ),
        migrations.CreateModel(
            name='Retrieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_the_child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.aboutthechild')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.location')),
                ('step1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.step1')),
                ('step3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.step3')),
            ],
        ),
    ]
