# Generated by Django 5.1 on 2024-08-24 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeEducatingForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutthechild',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.step1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.step1'),
        ),
        migrations.AlterField(
            model_name='step3',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeEducatingForm.step1'),
        ),
    ]
