# Generated by Django 5.1 on 2024-08-23 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_subjects', models.CharField(max_length=50)),
                ('years_of_experience', models.CharField(max_length=15)),
                ('expertise_area', models.CharField(max_length=90)),
                ('teaching_mode', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical'), ('Both', 'Both')], max_length=8)),
                ('time_available', models.JSONField()),
                ('days_available', models.JSONField()),
                ('preferred_online_tool', models.CharField(blank=True, max_length=15)),
                ('classes_you_teach', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_up_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
