# Generated by Django 5.1 on 2024-08-24 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_login_capturedimage_signupthree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signupthree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
