# Generated by Django 5.1 on 2024-08-24 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_capturedimage_user_alter_signupthree_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_work_experience', models.BooleanField(default=False)),
                ('no_work_experience', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
