# Generated by Django 5.1 on 2024-08-24 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageFirstRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Yoruba', 'Yoruba'), ('Igbo', 'Igbo'), ('French', 'French'), ('Hausa', 'Hausa'), ('German', 'German'), ('Spanish', 'Spanish'), ('Arabic', 'Arabic'), ('Chinese', 'Chinese')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=50)),
                ('students', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('how_soon', models.CharField(choices=[('Immediately', 'Immediately'), ('In a few days', 'In a few days'), ('In a few weeks', 'In a few weeks')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TechSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_student', models.CharField(choices=[('Parent', 'Parent'), ('Student', 'Student')], max_length=9)),
                ('l_name', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_available', models.JSONField()),
                ('program_duration', models.CharField(choices=[('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('Monthly', 'Monthly')], max_length=20)),
                ('hours_per_day', models.CharField(choices=[('1 hour', '1 hour'), ('1 hour 30 minutes', '1 hour 30 minutes'), ('2 hours', '2 hours'), ('2 hours 30 minutes', '2 hours 30 minutes'), ('3 hours', '3 hours'), ('4 hours', '4 hours')], max_length=20)),
                ('start_time', models.CharField(max_length=10)),
                ('student_level', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechandLanguageForm.languagefirstrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('preferred_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any Gender')], max_length=10)),
                ('teaching_mode', models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechandLanguageForm.languagelesson')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=30)),
                ('nearest_bus_stop', models.CharField(max_length=60)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='TechandLanguageForm.techskills')),
            ],
        ),
        migrations.CreateModel(
            name='TechskillsThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_day', models.CharField(max_length=15)),
                ('preferred_time', models.CharField(choices=[('Evening', 'Evening'), ('Afternoon', 'Afternoon')], max_length=12)),
                ('teaching_mode', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical')], max_length=8)),
                ('how_long', models.CharField(choices=[('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('Monthly', 'Monthly')], max_length=10)),
                ('starting_time', models.CharField(default=1, max_length=9)),
                ('days_available', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_users', to='TechandLanguageForm.techskills')),
            ],
        ),
        migrations.CreateModel(
            name='TechSkillsTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.CharField(max_length=8)),
                ('course', models.CharField(choices=[('UI/UX', 'UI/UX'), ('Front-end Development', 'Front-end Development'), ('Back-end Development', 'Back-end Development'), ('iOS and Android Development', 'iOS and Android Development')], max_length=50)),
                ('goal', models.CharField(choices=[('Develop interactive apps for educational use', 'Develop interactive apps for educational use'), ('Master coding fundamentals for app creation', 'Master coding fundamentals for app creation'), ('Create engaging UI/UX for diverse audiences', 'Create engaging UI/UX for diverse audiences'), ('Learn to integrate multimedia for impact', 'Learn to integrate multimedia for impact'), ('Build apps fostering learning and play', 'Build apps fostering learning and play'), ('Understand app deployment and maintenance basics', 'Understand app deployment and maintenance basics')], max_length=80)),
                ('tutor_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any gender is fine', 'Any gender is fine')], max_length=19)),
                ('about_the_child', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='TechandLanguageForm.techskills')),
            ],
        ),
    ]
